### ISSUE TITLE
Crash after re-creating native client

### ISSUE THREAD

**Issue by sywka** [asfernandes/node-firebird-driver-native#11]
If I run your example like this
```ts
test()
    .then(() => console.log("Finish..."))
    .then(test)
    .then(() => console.log("Finish..."))
    .catch(console.error);
```
I get error `Error: connection shutdown`

So it should be?

**Comment by asfernandes** [comment]
Are you connecting to a embedded or remote server?

**Comment by sywka** [comment]
embedded

**Comment by asfernandes** [comment]
Could you please try remote (may be localhost)?

**Comment by sywka** [comment]
The same result with localhost
