### ISSUE TITLE
Can not install using npm/yarn. Python required

### ISSUE THREAD

**Issue by gsbelarus** [asfernandes/node-firebird-driver-native#6]
There is an error during installation process. Seems that Python library required.

yarn add node-firebird-driver-native

>... 
>Output:
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.6.2
> gyp info using node@9.4.0 | win32 | x64
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.
> gyp ERR! stack     at PythonFinder.failNoPython (C:\\Golden\\NS\\lib\
> ode_modules\
> ode-gyp\\lib\\configure.js:483:19)
> gyp ERR! stack     at PythonFinder.<anonymous> (C:\\Golden\\NS\\lib\
> ode_modules\
> ode-gyp\\lib\\configure.js:508:16)
> gyp ERR! stack     at C:\\Golden\\NS\\lib\
> ode_modules\\graceful-fs\\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command \"C:\\\\Program Files\\\
>...

**Comment by asfernandes** [comment]
This is because it uses a native module, and node-gyp needs python in Windows. To not require it, it's necessary to pre-compile the binary and use node-pre-gyp. Contribution for this is welcome.

**Comment by gsbelarus** [comment]
But I have a Python 3.6 installed and still get an error.

**Comment by asfernandes** [comment]
Is it in PYTHON env. var. as the message request? Or in the PATH?

**Comment by gsbelarus** [comment]
both. but I will recheck tomorrow.

**Comment by gsbelarus** [comment]
Yes. Both path and PYTHON defined. and python.exe is accessible from command line but yarn/npm installation still laments that python is not available.

**Comment by asfernandes** [comment]
I do have in Windows Python 2.7.13 and Node 8.1.3 and it works. I do also have MSVC C++ installed.

**Comment by asfernandes** [comment]
Please see and try this https://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm
